# Generated by Django 5.2.1 on 2025-05-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempiApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pay', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('qualification', models.TextField(max_length=1000)),
                ('responsibilities', models.TextField(max_length=1000)),
                ('nice_to_haves', models.TextField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='TempiApp.category')),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='TempiApp.company')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
                ('job_type', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='TempiApp.jobtype')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='TempiApp_jo_title_99d798_idx'), models.Index(fields=['location'], name='TempiApp_jo_locatio_c3d184_idx'), models.Index(fields=['pay'], name='TempiApp_jo_pay_b85f74_idx'), models.Index(fields=['start_date'], name='TempiApp_jo_start_d_183104_idx'), models.Index(fields=['job_type'], name='TempiApp_jo_job_typ_10a530_idx'), models.Index(fields=['company'], name='TempiApp_jo_company_6d9648_idx'), models.Index(fields=['category'], name='TempiApp_jo_categor_3ba67a_idx')],
            },
        ),
    ]
