# Generated by Django 5.2.1 on 2025-08-25 20:22

from django.db import migrations


def add_shortlist_status(apps, schema_editor):
    Status = apps.get_model('TempiApp', 'Status')
    # Add Shortlisted status if it doesn't exist
    Status.objects.get_or_create(
        id=4,
        defaults={'name': 'Shortlisted'}
    )
    # Ensure Approved status exists (id=2)
    Status.objects.get_or_create(
        id=2,
        defaults={'name': 'Approved'}
    )


def remove_shortlist_status(apps, schema_editor):
    Status = apps.get_model('TempiApp', 'Status')
    # Remove Shortlisted status
    Status.objects.filter(id=4, name='Shortlisted').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('TempiApp', '0003_rating'),
    ]

    operations = [
        migrations.RunPython(add_shortlist_status, remove_shortlist_status),
    ]
