# Generated by Django 5.2.1 on 2025-08-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempiApp', '0004_add_shortlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='badge_earned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='has_best_employer_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badge_earned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_best_tempi_badge',
            field=models.BooleanField(default=False),
        ),
    ]
